"""rename address

Revision ID: 508dc3b154a6
Revises: 5624be7e3bdb
Create Date: 2026-02-16 11:22:11.489673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508dc3b154a6'
down_revision = '5624be7e3bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
