"""rename department

Revision ID: 5624be7e3bdb
Revises: 17c8b3bf2bb3
Create Date: 2026-02-16 11:17:30.833910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5624be7e3bdb'
down_revision = '17c8b3bf2bb3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
